### ISSUE TITLE
'name' should be name of the beneficiary, not name of the bank

### ISSUE THREAD

**Issue by tadwohlrapp** [Bitfertig/epc-qr-code.js#1]
Great little script, thank you for that!

Not a huge issue, but I noticed that you call the 'name' field _Bank Name_ with _Postbank_ as an example.
This field actually includes the name of the beneficiary. Bank name isn't used at all, that's what the BIC is for.

See [EPC guidelines](https://www.europeanpaymentscouncil.eu/sites/default/files/KB/files/EPC069-12%20v2.1%20Quick%20Response%20Code%20-%20Guidelines%20to%20Enable%20the%20Data%20Capture%20for%20the%20Initiation%20of%20a%20SCT.pdf) (Example on page 3)

**Comment by BitfertigAdmin** [comment]
Thank you. It is renamed now.
